# Generated by Django 4.2.5 on 2023-09-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="admin",
            fields=[
                (
                    "admin_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="管理员ID",
                    ),
                ),
                ("admin_name", models.CharField(max_length=255, verbose_name="管理员昵称")),
                ("admin_pw", models.CharField(max_length=10, verbose_name="管理员密码")),
                ("admin_power", models.CharField(max_length=255, verbose_name="管理员权限")),
            ],
        ),
        migrations.CreateModel(
            name="admin_log",
            fields=[
                (
                    "admin_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="管理员ID",
                    ),
                ),
                ("admin_act", models.CharField(max_length=255, verbose_name="管理员操作")),
                ("changetime", models.DateField(verbose_name="操作时间")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=255, verbose_name="用户昵称")),
                ("user_pw", models.CharField(max_length=10, verbose_name="用户密码")),
                (
                    "user_sex",
                    models.SmallIntegerField(
                        choices=[(0, "male"), (1, "female")],
                        default=0,
                        verbose_name="性别",
                    ),
                ),
                ("user_email", models.CharField(max_length=40, verbose_name="用户邮箱")),
                ("regist_date", models.DateField(verbose_name="注册日期")),
            ],
        ),
        migrations.CreateModel(
            name="User_friends",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=255, verbose_name="用户昵称")),
                ("friend_id", models.CharField(max_length=20, verbose_name="朋友ID")),
                ("friend_name", models.CharField(max_length=255, verbose_name="朋友昵称")),
            ],
        ),
        migrations.CreateModel(
            name="User_log",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=255, verbose_name="用户昵称")),
                ("act_name", models.CharField(max_length=255, verbose_name="用户动作")),
                ("keywords", models.CharField(max_length=255, verbose_name="搜索关键词")),
                ("uptime", models.DateField(verbose_name="上线时间")),
                ("downtime", models.DateField(verbose_name="下线时间")),
            ],
        ),
    ]
